### ISSUE TITLE
Attaching zip file to the release 

### ISSUE THREAD

**Issue by the-csaba** [OM4/weatherzone#3]
Currently, the `10up/action-wordpress-plugin-deploy` action has a bug and zip file not generated during WordPress deploy

Related bug: https://github.com/10up/action-wordpress-plugin-deploy/issues/52

As soon as the bug solved we can have zip upload action as well.

Proof of concept code:
```
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PLUGINS_GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/${{ github.event.repository.name }}.zip
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
```
